CREATE OR REPLACE PROCEDURE alert_wait
IS
  status INTEGER;
  mes    VARCHAR2(2000);
BEGIN
  DBMS_ALERT.REGISTER('ALERT_TEST');
  DBMS_ALERT.WAITONE('ALERT_TEST',mes,status,30);
  IF status = 1 THEN RETURN;
  END IF;
  DBMS_OUTPUT.PUT_LINE(mes);
  DBMS_ALERT.REMOVE('ALERT_TEST');
END;
/